main_app/main_app/authorization/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, login_required, logout_user
from werkzeug.security import check_password_hash, generate_password_hash
# импорт своего

# from main_app.authorization.env_change import env_change

# env_change.os_pythonpath_change()

# импорт моделей
from main_app.authorization.models import Users, db

from main_app.authorization import app_configs

app_configs=app_configs.load_configs()

from main_app.views import main_app, logging

# объявление модели
authorization_blueprint = Blueprint('authorization_blueprint', __name__)


@authorization_blueprint.route('/login', methods=['GET', 'POST'])
def login_page():
    login = request.form.get('login')
    password = request.form.get('password')

    if login and password:
        user = Users.query.filter_by(login=login).first()

        if user and check_password_hash(user.password, password):
            login_user(user)
            print(app_configs)
            # next_page = request.args.get('next')
            #
            # return redirect(next_page)
            # orders = [{
            #     "name": "ping",
            #     "parameter": "inclouds.bizml.ru"
            # },
            #     {
            #         "name": "http_get",
            #         "parameter": "https://inclouds.bizml.ru"
            #     }
            # ]
            # result=[]
            #
            # metrics = ["ping - inclouds.bizml.ru","http_get - https://inclouds.bizml.ru"]
            #
            # return render_template('main.html', user=Users.query.filter_by(login=login).first(), metrics=metrics, orders=result)
            users=db.session.execute('select * from users sd order by id')
            users=[dict(row) for row in users]
            scope_dir=db.session.execute('select * from scope_dir sd order by id')
            scope_dir=[dict(row) for row in scope_dir]
            result1=db.session.execute('select * from test')
            result1=[dict(row) for row in result1]
            # result=db.session.execute('select o.id, sd.id as id_scope_dir, sd.name, sd.describe, o.parameters, o.executors, o.status, sd2.job_frequency, sd2.job_frequency_type  from orders o inner join scope_dir sd on sd.id=o.id_scope_dir inner join users us on us.id=o.id_users inner join scheduler_dir sd2 on o.id=sd2.id_orders where us.login= :value1 order by o.id',{'value1': login})
            result=db.session.execute("""
            select o.id, sd.id as id_scope_dir, sd.name, sd.describe, o.parameters, o.executors, o.status, sd2.job_frequency, sd2.job_frequency_type  from orders o 
                    inner join scope_dir sd on sd.id=o.id_scope_dir 
                    inner join users us on us.id=o.id_users 
                    inner join scheduler_dir sd2 on o.id=sd2.id_orders 
                    where us.login= :login order by o.id
                    """,{'login': login})
            result=[dict(row) for row in result]

            # print("result: ", result)

            metrics = ["ping - inclouds.bizml.ru","http_get - https://inclouds.bizml.ru"]

            return render_template('main.html', user=Users.query.filter_by(login=login).first(), metrics=metrics, orders=result, test=result1, scope_dir=scope_dir, users=users, msk_scope=app_configs.get('MSK_SCOPE'))
        else:
            flash('Ошибка в логине или пароле')
    else:
        flash('Пожалуйста заполните поля учетной записи и пароля')

    return render_template('index.html')


@authorization_blueprint.route('/register', methods=['GET', 'POST'])
def register_page():
    login = request.form.get('login')
    password = request.form.get('password')
    password2 = request.form.get('password2')
    name = request.form.get('name')
    surname = request.form.get('surname')
    company = request.form.get('company')

    if request.method == 'POST':
        if not (login or password or password2):
            flash('Пожалуйста заполните все поля!')
        elif password != password2:
            flash('Пароль не совпадают!')
        else:
            hash_pwd = generate_password_hash(password)
            new_user = Users(login=login, password=hash_pwd, name=name, surname=surname, company=company)
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('index_start'))

    return render_template('register.html')


@authorization_blueprint.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('index_start'))


@authorization_blueprint.after_request
def redirect_to_signin(response):
    if response.status_code == 401:
        return redirect(url_for('authorization_blueprint.login_page') + '?next=' + request.url)

    return response

main_app/main_app/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
<!--    пришлось добавить из-за того что c HTTPS на HTTP -->
<!--    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">-->
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-4.5.3-dist/css/bootstrap.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='font-awesome/css/all.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<!--    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">-->

<!--        <a class="p-2 text-dark" href="/"><h5 class="my-0 mr-md-auto font-weight-normal">InClouds &copy;</h5></a>-->

<!--        <nav class="my-2 my-md-0 mr-md-3">-->
<!--            <a class="p-2 text-dark" href="/">Главная</a>-->
<!--            <a class="p-2 text-dark" href="/about">О нас</a>-->
<!--            <a class="p-2 text-dark" href="/posts">Статьи</a>-->
<!--        </nav>-->
<!--        <a class="btn btn-warning" href="/create-article">Создать</a>-->
<!--        <a class="btn btn-outline-primary" href="#">Sign up</a>-->

<nav class="navbar navbar-expand-sm bg-light">
    <a class="navbar-brand" href="/">InClouds 2.6&copy; 25.01.21</a>

<!--    &lt;!&ndash; Left &ndash;&gt;-->
<!--    <ul class="navbar-nav mr-auto">-->
<!--        <li class="nav-item">-->
<!--            <a class="nav-link">Java</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--            <a class="nav-link">C/C++</a>-->
<!--        </li>-->
<!--    </ul>-->
    <!-- Right -->
<!--    <ul class="navbar-nav ml-auto">-->
<!--        <li class="nav-item">-->
<!--            <a class="nav-link">Tom</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--            <a class="nav-link">Logout</a>-->
<!--        </li>-->
<!--    </ul>-->


    {% block head %}{% endblock %}
</nav>
   {% block body %}{% endblock %}
<!--    <footer class="container pt-4 my-md-5 pt-md-5 border-top">-->
<!--        <div class="row">-->
<!--            <div class="col-12 col-md">-->
<!--&lt;!&ndash;                <img class="mb-2" src="/docs/4.5/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">&ndash;&gt;-->
<!--                <small class="d-block mb-3 text-muted">&copy; 2017-2020</small>-->
<!--            </div>-->
<!--            <div class="col-6 col-md">-->
<!--                <h5>Features</h5>-->
<!--                <ul class="list-unstyled text-small">-->
<!--                    <li><a class="text-muted" href="#">Cool stuff</a></li>-->
<!--                    <li><a class="text-muted" href="#">Random feature</a></li>-->
<!--                    <li><a class="text-muted" href="#">Team feature</a></li>-->
<!--                    <li><a class="text-muted" href="#">Stuff for developers</a></li>-->
<!--                    <li><a class="text-muted" href="#">Another one</a></li>-->
<!--                    <li><a class="text-muted" href="#">Last time</a></li>-->
<!--                </ul>-->
<!--            </div>-->
<!--            <div class="col-6 col-md">-->
<!--                <h5>Resources</h5>-->
<!--                <ul class="list-unstyled text-small">-->
<!--                    <li><a class="text-muted" href="#">Resource</a></li>-->
<!--                    <li><a class="text-muted" href="#">Resource name</a></li>-->
<!--                    <li><a class="text-muted" href="#">Another resource</a></li>-->
<!--                    <li><a class="text-muted" href="#">Final resource</a></li>-->
<!--                </ul>-->
<!--            </div>-->
<!--            <div class="col-6 col-md">-->
<!--                <h5>About</h5>-->
<!--                <ul class="list-unstyled text-small">-->
<!--                    <li><a class="text-muted" href="#">Team</a></li>-->
<!--                    <li><a class="text-muted" href="#">Locations</a></li>-->
<!--                    <li><a class="text-muted" href="#">Privacy</a></li>-->
<!--                    <li><a class="text-muted" href="#">Terms</a></li>-->
<!--                </ul>-->
<!--            </div>-->
<!--        </div>-->
<!--    </footer>-->
    <footer class="container pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">

            </div>
        </div>
    </footer>
</body>
</html>

main_app/main_app/templates/index.html
{% extends 'base.html' %}

{% block title %}
InClouds (c)
{% endblock %}

{% block body %}

<div id="demo"></div>

<div class="container">

    <div class="row">
        <div class="col-md-8">
            <div class="thumbnail">
                <img src="" id="logo_src" alt="Lights" style="width:100%">
                <div id="myDiv"></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail">


                <form class="form-horizontal" method="POST" action="/login">

                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <ul class=flashes>
                        {% for message in messages %}
                        <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    {% endwith %}

                    <div class="form-group">
                        <label class="control-label col-sm-2" for="login">Логин:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="login" name="login" placeholder="Введите логин">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="password">Пароль:</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="password" name="password" placeholder="Введите пароль">
                        </div>
                    </div>
<!--                    <div class="form-group">-->
<!--                        <div class="col-sm-offset-2 col-sm-10">-->
<!--                            <div class="checkbox">-->
<!--                                <label><input type="checkbox"> Запомнить меня</label>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
<!--                            <a class="btn btn-outline-primary" href="{{ url_for('authorization_blueprint.login_page') }}">Войти</a>-->
                            <input type="submit" class="btn btn-outline-primary" value="Войти">
                            <a class="btn btn-outline-success" href="{{ url_for('authorization_blueprint.register_page') }}">Зарегистрировать</a>

                        </div>
                    </div>
                </form>

            </div>


        </div>
    </div>

</div>



<script>
    function randomInteger(min, max) {
        // получить случайное число от (min-0.5) до (max+0.5)
        let rand = min - 0.5 + Math.random() * (max - min + 1);
        return Math.round(rand);
    }
    // console.log(randomInteger(1,3));
    function get_logo_filename() {
        var variable1 = "images/logo"+randomInteger(1,5)+".jpg";
        var var1 = "{{ url_for('static', filename='ADDSHARE2') }}".replace("ADDSHARE2", variable1);

        return var1;
    }
    // console.log(get_logo_filename());
    // console.log(document.getElementById('demo'));
    document.getElementById('logo_src').src = get_logo_filename();
    // document.getElementById('myDiv').innerText='Fuck';
    // document.getElementById('myDiv').view = true;
    // console.log(document.getElementById('myDiv'));
</script>




<!--<div class="container">-->
<!--<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">-->
<!--    <h1 class="display-4">Pricing</h1>-->
<!--    <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>-->
<!--</div>-->

<!--        <div class="thumbnail">-->

<!--        </div>-->







<!--    <div class="card-deck mb-3 text-center">-->
<!--        <div class="card mb-4 shadow-sm">-->
<!--            <div class="col-md-8">-->
<!--       -->
<!--        </div>-->




<!--        </div>-->

<!--        <div class="card-deck mb-3 text-center">-->
<!--            <div class="card mb-2 shadow-sm">-->

<!--            </div>-->
<!--                <div class="card mb-5 shadow-sm">-->

<!--                </div>-->
<!--        </div>-->
<!--    <div class="card-deck mb-3 text-center">-->
<!--        <div class="card mb-4 shadow-sm">-->
<!--            <div class="card-header">-->
<!--                <h4 class="my-0 font-weight-normal">Free</h4>-->
<!--            </div>-->
<!--            <div class="card-body">-->
<!--                <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1>-->
<!--                <ul class="list-unstyled mt-3 mb-4">-->
<!--                    <li>10 users included</li>-->
<!--                    <li>2 GB of storage</li>-->
<!--                    <li>Email support</li>-->
<!--                    <li>Help center access</li>-->
<!--                </ul>-->
<!--                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Sign up for free</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="card mb-4 shadow-sm">-->
<!--            <div class="card-header">-->
<!--                <h4 class="my-0 font-weight-normal">Pro</h4>-->
<!--            </div>-->
<!--            <div class="card-body">-->
<!--                <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>-->
<!--                <ul class="list-unstyled mt-3 mb-4">-->
<!--                    <li>20 users included</li>-->
<!--                    <li>10 GB of storage</li>-->
<!--                    <li>Priority email support</li>-->
<!--                    <li>Help center access</li>-->
<!--                </ul>-->
<!--                <button type="button" class="btn btn-lg btn-block btn-primary">Get started</button>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="card mb-4 shadow-sm">-->
<!--            <div class="card-header">-->
<!--                <h4 class="my-0 font-weight-normal">Enterprise</h4>-->
<!--            </div>-->
<!--            <div class="card-body">-->
<!--                <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>-->
<!--                <ul class="list-unstyled mt-3 mb-4">-->
<!--                    <li>30 users included</li>-->
<!--                    <li>15 GB of storage</li>-->
<!--                    <li>Phone and email support</li>-->
<!--                    <li>Help center access</li>-->
<!--                </ul>-->
<!--                <button type="button" class="btn btn-lg btn-block btn-primary">Contact us</button>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

{% endblock %}

main_app/main_app/templates/register.html
{% extends 'base.html' %}

{% block title %}
InClouds (c)
{% endblock %}

{% block body %}

<div class="container">

    <div class="row">
        <div class="col-md-8">
            <div class="thumbnail">
                <img src="{{ url_for('static', filename='images/logo1.jpg') }}" alt="Lights" style="width:100%">
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail">

<!--                <form method="POST">-->
<!--                    <table>-->
<!--                        <tr>-->
<!--                            <td>Login</td>-->
<!--                            <td><input type="text" name="login"></td>-->
<!--                        </tr>-->
<!--                        <tr>-->
<!--                            <td>Password</td>-->
<!--                            <td><input type="password" name="password"></td>-->
<!--                        </tr>-->
<!--                        <tr>-->
<!--                            <td>Password retype</td>-->
<!--                            <td><input type="password" name="password2"></td>-->
<!--                        </tr>-->
<!--                        <tr>-->
<!--                            <td><a href="{{ url_for('authorization_blueprint.login_page') }}">Login</a></td>-->
<!--                            <td><input type="submit" value="Register"></td>-->
<!--                        </tr>-->
<!--                    </table>-->
<!--                </form>-->


<!--                <form class="form-horizontal" method="POST">-->


                <form method="POST">
                        <label class="control-label col-sm-2" for="login">Регистрация нового пользователя</label>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="login">Логин:</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="login" name="login" placeholder="Введите логин">
                            </div>
                        </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="password">Пароль:</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="password" name="password" placeholder="Введите пароль">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="password2">Повторите пароль:</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="password2" name="password2" placeholder="Введите пароль">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="name">Имя:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="name" name="name" placeholder="Введите имя">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="surname">Фамилия:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="surname" name="surname" placeholder="Введите фамилию">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="company">Введите наименование компании:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="company" name="company" placeholder="Введите наименование компании">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input type="submit" class="btn btn-outline-success" value="Зарегистрировать">
                        </div>
                    </div>


                </form>


            </div>


        </div>
    </div>

</div>





</div>
</div>
{% endblock %}